--

=======================================

=============================
-- PROJECT: IT Help Desk Ticket Management
Database
-- AUTHOR: Vuk Bojkovic
-- LANGUAGE: Oracle SQL & PL/SQL
-- DESCRIPTION: Database schema for tracking
IT support tickets,
-- customer issues, SLA resolution, and
technician assignments.
--

=======================================

=============================

-- 1. CLEAN UP (Drop tables if they already exist for easy testing)
BEGIN
FOR t IN (SELECT table_name FROM user_tables
WHERE table_name IN ('TICKETS', 'TECHNICIANS', 'USERS')) LOOP
EXECUTE IMMEDIATE 'DROP TABLE ' ||
t.table_name || ' CASCADE CONSTRAINTS';
END LOOP;
END;
/

-- 2. CREATE DATABASE TABLES WITH
INTEGRITY CONSTRAINTS
CREATE TABLE USERS (
user_id NUMBER GENERATED BY DEFAULT AS
IDENTITY PRIMARY KEY,
first_name VARCHAR2(50) NOT NULL,
last_name VARCHAR2(50) NOT NULL,
email VARCHAR2(100) UNIQUE NOT NULL,
department VARCHAR2(50) NOT NULL
);

CREATE TABLE TECHNICIANS (
tech_id NUMBER GENERATED BY DEFAULT AS

IDENTITY PRIMARY KEY,
first_name VARCHAR2(50) NOT NULL,
last_name VARCHAR2(50) NOT NULL,
tier_level NUMBER CHECK (tier_level IN (1, 2, 3)),
-- Support tiers (L1, L2, L3)
status VARCHAR2(15) DEFAULT 'AVAILABLE'
CHECK (status IN ('AVAILABLE', 'BUSY',
'ON_LEAVE'))
);

CREATE TABLE TICKETS (
ticket_id NUMBER GENERATED BY DEFAULT AS
IDENTITY PRIMARY KEY,
user_id NUMBER NOT NULL,
tech_id NUMBER,
title VARCHAR2(100) NOT NULL,
priority VARCHAR2(10) CHECK (priority IN
('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
status VARCHAR2(15) DEFAULT 'OPEN' CHECK
(status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED')),
created_at DATE DEFAULT SYSDATE NOT NULL,
resolved_at DATE,
CONSTRAINT fk_ticket_user FOREIGN KEY
(user_id) REFERENCES USERS(user_id) ON
DELETE CASCADE,
CONSTRAINT fk_ticket_tech FOREIGN KEY
(tech_id) REFERENCES TECHNICIANS(tech_id)
ON DELETE SET NULL
);

-- 3. INSERT RELEVANT SAMPLE DATA
INSERT INTO USERS (first_name, last_name,
email, department) VALUES ('Ana', 'Antic',
'ana.antic@company.com', 'Finance');

INSERT INTO USERS (first_name, last_name,
email, department) VALUES ('Milovan',
'Milovanovic', 'm.milovanovic@company.com',
'HR');

INSERT INTO USERS (first_name, last_name,
email, department) VALUES ('Jelena', 'Jovanovic',
'jelena.j@company.com', 'Marketing');

INSERT INTO TECHNICIANS (first_name,
last_name, tier_level, status) VALUES ('Igor',
'Ignovic', 1, 'AVAILABLE');

INSERT INTO TECHNICIANS (first_name,
last_name, tier_level, status) VALUES ('Nemanja',
'Nikolic', 2, 'BUSY');

INSERT INTO TICKETS (user_id, tech_id, title,
priority, status) VALUES (1, 1, 'Cannot connect to
VPN from home Office', 'HIGH', 'IN_PROGRESS');

INSERT INTO TICKETS (user_id, tech_id, title,
priority, status) VALUES (2, 2, 'Oracle Database
connection timed out', 'CRITICAL', 'OPEN');

INSERT INTO TICKETS (user_id, tech_id, title,
priority, status) VALUES (3, NULL, 'Printer in
Room 302 needs toner replacement', 'LOW',

'OPEN');
COMMIT;

-- 4. ANALYTICAL BUSINESS QUERY WITH JOIN
-- Goal: Get a clear overview of all active critical and high priority tickets
SELECT
t.ticket_id,
t.title AS ticket_issue,
t.priority,
t.status AS ticket_status,
u.first_name || ' ' || u.last_name AS reported_by,
u.department,
NVL(tech.first_name || ' ' || tech.last_name,
'UNASSIGNED') AS assigned_technician
FROM TICKETS t
JOIN USERS u ON t.user_id = u.user_id
LEFT JOIN TECHNICIANS tech ON t.tech_id =
tech.tech_id

WHERE t.priority IN ('HIGH', 'CRITICAL') AND
t.status != 'RESOLVED'
ORDER BY t.created_at DESC;

-- 5. PL/SQL STORED FUNCTION
-- Goal: Calculate total number of open tickets for a specific technician
CREATE OR REPLACE FUNCTION
get_tech_open_tickets(p_tech_id IN NUMBER)
RETURN NUMBER IS
v_ticket_count NUMBER := 0;
BEGIN
SELECT COUNT(*)
INTO v_ticket_count
FROM TICKETS
WHERE tech_id = p_tech_id AND status IN
('OPEN', 'IN_PROGRESS');

RETURN v_ticket_count;

END;
/

-- 6. PL/SQL DATABASE TRIGGER
-- Goal: Automatically update resolved_at date when ticket status changes to RESOLVED
CREATE OR REPLACE TRIGGER
trg_set_resolved_date
BEFORE UPDATE ON TICKETS
FOR EACH ROW
BEGIN
IF :NEW.status = 'RESOLVED' AND :OLD.status !=
'RESOLVED' THEN
:NEW.resolved_at := SYSDATE;
END IF;
END;
/
